/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pager2 */

#ifndef _Included_Pager2
#define _Included_Pager2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pager2
 * Method:    page
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Pager2_page
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Pager2
 * Method:    who
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Pager2_who
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
