/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pager */

#ifndef _Included_Pager
#define _Included_Pager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pager
 * Method:    page
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Pager_page
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
