/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CCCheck */

#ifndef _Included_CCCheck
#define _Included_CCCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CCCheck
 * Method:    validCC
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_CCCheck_validCC
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
