/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StockMarketEngine */

#ifndef _Included_StockMarketEngine
#define _Included_StockMarketEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StockMarketEngine
 * Method:    addStockListener
 * Signature: (LStockListener;)V
 */
JNIEXPORT void JNICALL Java_StockMarketEngine_addStockListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     StockMarketEngine
 * Method:    startEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StockMarketEngine_startEngine
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
